spring:
  data:
    mongodb:
      uri: mongodb+srv://andresestrada0630_db_user:prestamosDeportivos@prestamos.aygd11w.mongodb.net/?retryWrites=true&w=majority&appName=prestamos
      database: prestamos

server:
  port: 8080

jwt:
  secret: PMkh0Vxta3KLaGc0tLnLteh+M$/vq^Na#icp3yZKbD0=
  expiration: 7200000

logging:
  level:
    org:
      springframework:
        data:
          mongodb: INFO
    com:
      prestamos: INFO
